# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171108_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('userid1', models.IntegerField(db_column='userID1', primary_key=True, serialize=False)),
                ('userid2', models.IntegerField(db_column='userID2')),
            ],
            options={
                'db_table': 'friend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('userid', models.IntegerField(db_column='userID', primary_key=True, serialize=False)),
                ('movieid', models.IntegerField(db_column='movieID')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'wish',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
